name: Summarize Repository

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python and dir-diary
      uses: Promptly-Technologies-LLC/setup-dir-diary@v1
      with:
        install-python: 'true'

    - name: Load OpenAI API Key from GitHub Secrets
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run dir-diary summarize command
      run: summarize --startpath="./"

    - name: Stage changes
      run: git add -A

    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

    - name: Pull latest changes
      if: steps.git-check.outputs.modified == 'true'
      run: git pull origin main

    - name: Commit and push if modified
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git commit -m "Automated summarization"
        git push
